import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { Copy, Download, Edit, Paperclip, Plus, Trash2, Check } from 'lucide-react';
import { useAuth } from '../hooks/useAuth';
import { useData } from '../hooks/useData';
import { supabase, checkError } from '../lib/supabase';
import { canEditCase, formatDate, handlingHours, urgency } from '../lib/analytics';
import type { Attachment, CaseActivity, CaseComment, Lifecycle, Reminder, Visibility } from '../lib/types';
import { Badge, Card, Empty, ErrorMessage, Loading, PageHead } from '../components/UI';
export default function CaseDetail(){
  const {id}=useParams();const {cases,profiles,config,refresh}=useData();const {profile}=useAuth();const navigate=useNavigate();
  const c=cases.find(c=>c.id===id);const editable=c?canEditCase(c,profile!):false;
  const requester=profile!.role==='Requester';const manager=profile!.role==='Team Leader'||profile!.role==='Admin';
  const [comments,setComments]=useState<CaseComment[]>([]),[activity,setActivity]=useState<CaseActivity[]>([]),[attachments,setAttachments]=useState<Attachment[]>([]),[reminders,setReminders]=useState<Reminder[]>([]);
  const [internal,setInternal]=useState(''),[legacy,setLegacy]=useState<unknown>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
  const [comment,setComment]=useState(''),[visibility,setVisibility]=useState<Visibility>(requester?'Requester':'Internal'),[status,setStatus]=useState<Lifecycle>(c?.lifecycle||'Probing'),[resolution,setResolution]=useState(c?.resolution_summary||''),[reason,setReason]=useState(c?.closure_reason||''),[escalation,setEscalation]=useState(c?.escalation_reason||''),[followUp,setFollowUp]=useState('');
  const [primary,setPrimary]=useState(c?.primary_pic_id||''),[linkedRequester,setLinkedRequester]=useState(c?.requester_id||''),[collaborators,setCollaborators]=useState(c?.collaborator_ids||[]);
  async function load(){
    setLoading(true);
    try{
      const [a,b,d,e,f]=await Promise.all([
        supabase.from('case_comments').select('*').eq('case_id',id!).order('created_at'),
        supabase.from('case_activity').select('*').eq('case_id',id!).order('created_at'),
        supabase.from('attachments').select('*').eq('case_id',id!).order('created_at'),
        requester?Promise.resolve({data:[],error:null}):supabase.from('reminders').select('*').eq('case_id',id!).order('due_at'),
        requester?Promise.resolve({data:null,error:null}):supabase.from('case_internal').select('internal_note,legacy_source').eq('case_id',id!).maybeSingle(),
      ]);
      [a,b,d,e,f].forEach(x=>checkError(x.error));setComments(a.data as CaseComment[]);setActivity(b.data as CaseActivity[]);setAttachments(d.data as Attachment[]);setReminders(e.data as Reminder[]);setInternal(f.data?.internal_note||'');setLegacy(f.data?.legacy_source||null);
    }catch(e){setError(e instanceof Error?e.message:String(e));}finally{setLoading(false);}
  }
  useEffect(()=>{void load();},[id]);
  async function run(action:()=>Promise<void>,success:string){setBusy(true);setError('');setMessage('');try{await action();await refresh();await load();setMessage(success);}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
  if(!c)return <><PageHead title="Case unavailable"/><Empty text="This case does not exist or is outside your account’s access scope."/><Link className="link" to="/cases">Back to Cases</Link></>;
  function update(){void run(async()=>{
    const data:Record<string,unknown>={lifecycle:status,resolution_summary:resolution,closure_reason:reason};
    if(status==='Closed'&&(!resolution.trim()||!reason.trim()))throw new Error('Enter a resolution summary and closure reason.');
    if(followUp)data.follow_up_date=new Date(followUp).toISOString();
    const {data:updated,error}=await supabase.from('cases').update(data).eq('id',id!).select('id').single();checkError(error);if(!updated)throw new Error('This case could not be updated.');
  },'Case updated.');}
  async function upload(file:File){
    if(file.size>10485760)throw new Error('Use a file smaller than 10 MB.');
    const path=id+'/'+crypto.randomUUID()+'-'+file.name.replace(/[^a-zA-Z0-9._-]/g,'_');
    const {error}=await supabase.storage.from('case-attachments').upload(path,file);checkError(error);
    const {error:metaError}=await supabase.from('attachments').insert({case_id:id!,uploaded_by:profile!.id,name:file.name,path,size:file.size});
    if(metaError){await supabase.storage.from('case-attachments').remove([path]);throw new Error(metaError.message);}
  }
  return <><PageHead title={c.ticket} description={c.subject}><button className="btn secondary" onClick={()=>navigate(-1)}>Back</button>{editable?<button className="btn primary" onClick={()=>navigate('/cases/'+c.id+'/edit')}><Edit size={16}/>Edit Case</button>:null}</PageHead>
  <ErrorMessage message={error}/>{message?<div className="success-msg" role="status">{message}</div>:null}
  <div className="detail-layout"><div>
  <Card title="Ticket Detail"><div className="status-row"><Badge text={c.lifecycle}/><Badge text={urgency(c,config)}/>{c.is_draft?<Badge text="Draft"/>:null}<span className="small">{handlingHours(c,config).toFixed(1)} elapsed hours</span></div><div className="life-track">{['Probing','In Progress','Waiting Support','Closed'].map((s,i)=><div className={'life-step '+(i<['Probing','In Progress','Waiting Support','Closed'].indexOf(c.lifecycle)?'done':s===c.lifecycle?'current':'')} key={s}>{s}</div>)}</div>
  <dl className="detail-grid">{[['Requester',c.requester_name],['Requester Unit',c.requester_unit],['Region',c.region],['Segment / Origin',c.segment],['Customer',c.customer_name],['Counterpart',c.counterpart],['Contact',c.contact],['Channel',c.channel],['Product',c.product],['Category',c.category],['Original Category',c.raw_category],['Subcategory',c.subcategory],['Reference Number',c.reference_no],['Primary PIC',c.primary_pic_name],['Collaborators',c.collaborator_names.join(', ')],['Supporting Unit',c.supporting_unit],['Involvement',c.involvement],['Priority',c.priority],['Created',formatDate(c.created_at)],['Last Update',formatDate(c.updated_at)],['Next Follow-up',formatDate(c.follow_up_date)]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value||'—'}</dd></div>)}</dl>
  <h4>Description</h4><p className="preserve-text">{c.description}</p>{c.additional_info?<><h4>Additional Information</h4><p className="preserve-text">{c.additional_info}</p></>:null}{c.resolution_summary?<><h4>Resolution Summary</h4><p className="preserve-text">{c.resolution_summary}</p><p className="small">{c.closure_reason} • {formatDate(c.closure_date)}</p></>:null}</Card>
  {!requester?<Card title="Internal Notes" className="spaced">{editable?<><textarea aria-label="Internal case note" value={internal} onChange={e=>setInternal(e.target.value)} rows={3}/><button className="btn secondary" disabled={busy} onClick={()=>void run(async()=>{const {error}=await supabase.from('case_internal').upsert({case_id:id!,internal_note:internal});checkError(error);},'Internal note saved.')}>Save Internal Note</button></>:<p className="preserve-text">{internal||'No internal notes.'}</p>}{legacy?<details className="legacy-record"><summary>Original imported record</summary><pre>{JSON.stringify(legacy,null,2)}</pre></details>:null}</Card>:null}
  <Card title="Comments" className="spaced">{loading?<Loading text="Loading case history…"/>:comments.length?comments.map(x=><div className="comment" key={x.id}><strong>{x.author_name}</strong><span className="small"> {formatDate(x.created_at)} • {x.visibility}</span><p className="preserve-text">{x.body}</p></div>):<Empty text="No comments yet."/>}
  {editable||requester?<form onSubmit={e=>{e.preventDefault();void run(async()=>{const {error}=await supabase.from('case_comments').insert({case_id:id!,author_id:profile!.id,author_name:profile!.full_name,body:comment.trim(),visibility});checkError(error);setComment('');},'Comment posted.');}}><label htmlFor="commentBody" className="small">Add a comment</label><textarea id="commentBody" value={comment} onChange={e=>setComment(e.target.value)} rows={3} required/><div className="action-buttons">{!requester?<select aria-label="Comment visibility" value={visibility} onChange={e=>setVisibility(e.target.value as Visibility)}><option>Internal</option><option>Requester</option></select>:null}<button className="btn primary" disabled={busy||!comment.trim()}>Post Comment</button></div></form>:null}</Card>
  <Card title="Activity Timeline" className="spaced">{activity.length?activity.map(a=><div className="event" key={a.id}><strong>{a.action}</strong><div className="event-meta">{formatDate(a.created_at)} • {a.actor_name} • {a.visibility}</div>{a.previous_status&&a.previous_status!==a.next_status?<p>{a.previous_status} → {a.next_status}</p>:null}{a.body?<p>{a.body}</p>:null}</div>):<Empty text="No activity recorded."/>}</Card>
  </div><aside>
  {editable?<Card title="Case Actions"><label className="field">Lifecycle<select aria-label="Lifecycle" value={status} onChange={e=>setStatus(e.target.value as Lifecycle)}>{['Probing','In Progress','Waiting Support','Closed'].map(s=><option key={s}>{s}</option>)}</select></label><label className="field">Resolution Summary<textarea value={resolution} onChange={e=>setResolution(e.target.value)} rows={4}/></label><label className="field">Closure / Reopen Reason<textarea value={reason} onChange={e=>setReason(e.target.value)} rows={2}/></label><label className="field">Next Follow-up<input type="datetime-local" value={followUp} onChange={e=>setFollowUp(e.target.value)}/></label><button className="btn primary" disabled={busy} onClick={update}>Update Case</button><div className="divider"/><label className="field">Escalation Reason<textarea value={escalation} onChange={e=>setEscalation(e.target.value)} rows={2}/></label><button className="btn secondary" disabled={busy||!escalation.trim()} onClick={()=>void run(async()=>{const {error}=await supabase.from('cases').update({escalation_status:'Escalated',escalation_reason:escalation}).eq('id',id!);checkError(error);},'Case escalated.')}>Escalate Case</button><p className="small">Current: {c.escalation_status}</p></Card>:null}
  {manager?<Card title="Assignments & Requester Access" className="spaced"><label className="field">Primary PIC<select value={primary} onChange={e=>setPrimary(e.target.value)}><option value="">Unassigned</option>{profiles.filter(p=>p.role==='TSCC User'||p.role==='Team Leader').map(p=><option key={p.id} value={p.id}>{p.full_name}</option>)}</select></label><label className="field">Requester Account<select value={linkedRequester} onChange={e=>setLinkedRequester(e.target.value)}><option value="">Unlinked</option>{profiles.filter(p=>p.role==='Requester').map(p=><option key={p.id} value={p.id}>{p.full_name} ({p.email})</option>)}</select></label><div className="field"><label>Collaborating PICs</label>{profiles.filter(p=>p.role==='TSCC User'&&p.id!==primary).map(p=><label className="checkbox-label" key={p.id}><input type="checkbox" checked={collaborators.includes(p.id)} onChange={e=>setCollaborators(e.target.checked?[...collaborators,p.id]:collaborators.filter(i=>i!==p.id))}/>{p.full_name}</label>)}</div><button className="btn secondary" disabled={busy} onClick={()=>void run(async()=>{const person=profiles.find(p=>p.id===primary);const {error}=await supabase.from('cases').update({primary_pic_id:primary||null,primary_pic_name:person?.full_name||c.primary_pic_name,requester_id:linkedRequester||null,collaborator_ids:collaborators,collaborator_names:collaborators.map(i=>profiles.find(p=>p.id===i)?.full_name||'')}).eq('id',id!);checkError(error);},'Assignments updated.')}>Save Assignments</button></Card>:null}
  <Card title="Attachments" className="spaced">{attachments.length?attachments.map(a=><div className="attachment-row" key={a.id}><div><strong>{a.name}</strong><span>{(a.size/1024).toFixed(1)} KB</span></div><button className="link" aria-label={'Download '+a.name} onClick={()=>void run(async()=>{const {data,error}=await supabase.storage.from('case-attachments').createSignedUrl(a.path,60,{download:a.name});checkError(error);const link=document.createElement('a');link.href=data!.signedUrl;link.download=a.name;link.click();},'Download ready.')}><Download size={16}/></button>{editable?<button className="link" aria-label={'Remove '+a.name} onClick={()=>void run(async()=>{const {error}=await supabase.storage.from('case-attachments').remove([a.path]);checkError(error);const {error:meta}=await supabase.from('attachments').delete().eq('id',a.id);checkError(meta);},'Attachment removed.')}><Trash2 size={16}/></button>:null}</div>):<p className="small">No attachments.</p>}{editable?<label className="btn secondary upload-label"><Paperclip size={16}/>Upload File<input type="file" className="sr-only" onChange={e=>{const file=e.target.files?.[0];if(file)void run(()=>upload(file),'Attachment uploaded.');e.target.value='';}}/></label>:null}</Card>
  {!requester?<Card title="Reminders" className="spaced">{reminders.map(r=><div className="attachment-row" key={r.id}><div><strong>{r.note||'Follow-up'}</strong><span>{formatDate(r.due_at)} • {r.completed?'Completed':'Upcoming'}</span></div>{editable?<button className="link" aria-label={r.completed?'Reopen reminder':'Complete reminder'} onClick={()=>void run(async()=>{const {error}=await supabase.from('reminders').update({completed:!r.completed}).eq('id',r.id);checkError(error);},'Reminder updated.')}><Check size={16}/></button>:null}</div>)}{editable?<form onSubmit={e=>{e.preventDefault();const form=e.currentTarget,fd=new FormData(form);void run(async()=>{const {error}=await supabase.from('reminders').insert({case_id:id!,owner_id:profile!.id,due_at:new Date(String(fd.get('date'))).toISOString(),note:String(fd.get('note'))});checkError(error);form.reset();},'Reminder saved.');}}><label className="field">Reminder Date<input name="date" type="datetime-local" required/></label><label className="field">Note<input name="note" required/></label><button className="btn secondary" disabled={busy}><Plus size={15}/>Add Reminder</button></form>:null}</Card>:null}
  <Card title="Share Ticket" className="spaced"><p className="small">Copy a reference link. Recipients must sign in with an account authorized to view this case.</p><button className="btn secondary" onClick={()=>void navigator.clipboard.writeText(window.location.origin+'/cases/'+c.id).then(()=>setMessage('Ticket link copied.')).catch(()=>setError('Unable to copy. Copy the URL from your browser.'))}><Copy size={15}/>Copy Ticket Link</button></Card>
  {!requester?<Card title="Similar Closed Cases" className="spaced">{cases.filter(x=>x.id!==c.id&&x.lifecycle==='Closed'&&x.product===c.product&&x.category===c.category).slice(0,4).map(x=><Link className="similar-item" to={'/cases/'+x.id} key={x.id}><strong>{x.ticket}</strong><p>{x.subject}</p><span className="small">{x.actual_handling_hours?.toFixed(1)||'—'} handling hours</span></Link>)}</Card>:null}
  </aside></div></>;
}