import { useState } from 'react';
import { useData } from '../hooks/useData';
import { supabase, checkError } from '../lib/supabase';
import { type Profile, type Role } from '../lib/types';
import { Card, ErrorMessage, PageHead } from '../components/UI';
import { groupCases } from '../lib/analytics';
const roles:Role[]=['Requester','TSCC User','Team Leader','Department Head','Admin'];
export default function Configuration(){
  const {config,cases,profiles,refresh}=useData();const [settings,setSettings]=useState(config),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[search,setSearch]=useState('');
  const [edited,setEdited]=useState<Profile|null>(null),[legacyPic,setLegacyPic]=useState(''),[target,setTarget]=useState('');
  async function run(action:()=>Promise<void>,success:string){setBusy(true);setError('');setMessage('');try{await action();await refresh();setMessage(success);}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
  return <><PageHead title="Configuration" description="TAT rules, master data, and account access."/><ErrorMessage message={error}/>{message?<div className="success-msg" role="status">{message}</div>:null}
  <div className="grid2"><Card title="TAT Configuration"><form onSubmit={e=>{e.preventDefault();void run(async()=>{if(Object.values(settings.tatHours).some(v=>!Number.isFinite(v)||v<=0))throw new Error('TAT targets must be positive.');const {error}=await supabase.from('configuration').update({value:settings}).eq('id',true);checkError(error);},'Configuration saved.');}}>{settings.involvement.map(key=><label className="config-row" key={key}><span>{key} (hours)</span><input type="number" min={1} required value={settings.tatHours[key]} onChange={e=>setSettings({...settings,tatHours:{...settings.tatHours,[key]:Number(e.target.value)}})}/></label>)}<label className="config-row"><span>Pause TAT in Waiting Support</span><select value={String(settings.pauseWaitingSupport)} onChange={e=>setSettings({...settings,pauseWaitingSupport:e.target.value==='true'})}><option value="false">No</option><option value="true">Yes</option></select></label><button className="btn primary" disabled={busy}>Save TAT Rules</button></form></Card><Card title="Master Data">{(['products','categories','subcategories','regions','channels','requesterUnits','supportUnits'] as const).map(key=><details key={key}><summary>{key} — {settings[key].length} values</summary><label className="field"><span className="small">One value per line</span><textarea rows={5} value={settings[key].join('\n')} onChange={e=>setSettings({...settings,[key]:e.target.value.split('\n')})}/></label></details>)}<button className="btn secondary" disabled={busy} onClick={()=>void run(async()=>{const clean={...settings};for(const key of ['products','categories','subcategories','regions','channels','requesterUnits','supportUnits'] as const)clean[key]=[...new Set(clean[key].map(s=>s.trim()).filter(Boolean))];const {error}=await supabase.from('configuration').update({value:clean}).eq('id',true);checkError(error);setSettings(clean);},'Master data saved.')}>Save Master Data</button></Card></div>
  <Card title="Account Access" className="spaced" subtitle="Invite users through Supabase Authentication, then assign their organizational role here."><div className="table-wrap"><table><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Unit</th><th>Region</th><th></th></tr></thead><tbody>{profiles.map(p=><tr key={p.id}><td>{p.full_name}</td><td>{p.email}</td><td>{p.role}</td><td>{p.unit}</td><td>{p.region}</td><td><button className="link" onClick={()=>setEdited({...p})}>Edit Access</button></td></tr>)}</tbody></table></div>{edited?<form className="form-grid spaced-text" onSubmit={e=>{e.preventDefault();void run(async()=>{const {error}=await supabase.from('profiles').update({role:edited.role,unit:edited.unit,region:edited.region,npp:edited.npp,full_name:edited.full_name}).eq('id',edited.id);checkError(error);setEdited(null);},'Account access updated.');}}><label className="field">Full Name<input value={edited.full_name} onChange={e=>setEdited({...edited,full_name:e.target.value})}/></label><label className="field">Role<select value={edited.role} onChange={e=>setEdited({...edited,role:e.target.value as Role})}>{roles.map(r=><option key={r}>{r}</option>)}</select></label>{(['unit','region','npp'] as const).map(key=><label className="field" key={key}>{key}<input value={edited[key]} onChange={e=>setEdited({...edited,[key]:e.target.value})}/></label>)}<div className="action-buttons full"><button className="btn primary" disabled={busy}>Save Access</button><button type="button" className="link" onClick={()=>setEdited(null)}>Cancel</button></div></form>:null}</Card>
  <Card title="Link Imported PIC Assignments" className="spaced" subtitle="Map a legacy PIC identity to an authenticated staff account."><form className="filters" onSubmit={e=>{e.preventDefault();void run(async()=>{const person=profiles.find(p=>p.id===target);if(!person)throw new Error('Choose a staff account.');const {error}=await supabase.from('cases').update({primary_pic_id:person.id,primary_pic_name:person.full_name}).eq('primary_pic_name',legacyPic).is('primary_pic_id',null);checkError(error);},'Imported primary assignments linked. Collaborating assignments can be edited in each case.');}}><select aria-label="Legacy PIC" value={legacyPic} onChange={e=>setLegacyPic(e.target.value)} required><option value="">Select legacy PIC</option>{groupCases(cases,'primary_pic_name').map(([name,list])=><option key={name} value={name}>{name} ({list.length})</option>)}</select><select aria-label="Authenticated staff account" value={target} onChange={e=>setTarget(e.target.value)} required><option value="">Select staff account</option>{profiles.filter(p=>p.role==='TSCC User'||p.role==='Team Leader').map(p=><option key={p.id} value={p.id}>{p.full_name}</option>)}</select><button className="btn secondary" disabled={busy}>Link Assignments</button></form></Card>
  <Card title="Requester Master" className="spaced" subtitle="Source identities are shown for reference. Ticket access requires an explicit account link." actions={<input aria-label="Search requester names" placeholder="Search requester name…" value={search} onChange={e=>setSearch(e.target.value)}/>}><div className="table-wrap"><table><thead><tr><th>Requester Name</th><th>Unit</th><th>Region</th><th>Tickets</th><th>Linked Account</th></tr></thead><tbody>{groupCases(cases,'requester_name').filter(([name])=>name.toLowerCase().includes(search.toLowerCase())).slice(0,100).map(([name,list])=><tr key={name}><td>{name}</td><td>{[...new Set(list.map(c=>c.requester_unit))].join(', ')}</td><td>{[...new Set(list.map(c=>c.region))].join(', ')}</td><td>{list.length}</td><td>{list.some(c=>c.requester_id)?'Linked on individual tickets':'Unlinked'}</td></tr>)}</tbody></table></div><p className="small">Showing up to 100 matching identities.</p></Card></>;
}
