import { useEffect, useState } from 'react';
import { useAuth } from '../hooks/useAuth';
import { useData } from '../hooks/useData';
import { supabase, checkError } from '../lib/supabase';
import { Card, ErrorMessage, PageHead } from '../components/UI';
export default function Profile(){
  const {profile,refreshProfile}=useAuth();const {refresh}=useData();
  const [name,setName]=useState(profile!.full_name),[phone,setPhone]=useState(profile!.phone),[avatar,setAvatar]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
  useEffect(()=>{if(profile!.avatar_path){supabase.storage.from('avatars').createSignedUrl(profile!.avatar_path,300).then(({data,error})=>{if(error)setError(error.message);else setAvatar(data!.signedUrl);});}else setAvatar('');},[profile!.avatar_path]);
  async function save(data:Record<string,unknown>){setBusy(true);setError('');setMessage('');try{const {error}=await supabase.from('profiles').update(data).eq('id',profile!.id);checkError(error);await refreshProfile();await refresh();setMessage('Profile updated.');}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
  async function upload(file:File){setBusy(true);setError('');try{if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>1048576)throw new Error('Use a JPG, PNG, or WebP image smaller than 1 MB.');const path=profile!.id+'/'+crypto.randomUUID()+'.'+(file.type==='image/jpeg'?'jpg':file.type.split('/')[1]);const {error}=await supabase.storage.from('avatars').upload(path,file);checkError(error);await save({avatar_path:path});}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
  return <><PageHead title="Profile" description="Personal information and system-managed organizational details."/><ErrorMessage message={error}/>{message?<div className="success-msg" role="status">{message}</div>:null}<div className="profile-layout"><Card className="profile-photo-card"><div className="profile-photo">{avatar?<img src={avatar} alt={profile!.full_name}/>:profile!.full_name.split(' ').map(x=>x[0]).slice(0,2).join('')}</div><h3>{profile!.full_name}</h3><p className="small">{profile!.role}</p><label className="btn secondary">Change Photo<input type="file" accept="image/png,image/jpeg,image/webp" className="sr-only" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file);e.target.value='';}}/></label>{avatar?<button className="btn secondary" disabled={busy} onClick={()=>void save({avatar_path:null})}>Remove Photo</button>:null}</Card><Card title="Personal Information"><form onSubmit={e=>{e.preventDefault();void save({full_name:name.trim(),phone:phone.trim()});}}><div className="profile-form-grid"><label className="field">Full Name <span className="small">Editable</span><input value={name} onChange={e=>setName(e.target.value)} required/></label><label className="field">Phone / Extension <span className="small">Editable</span><input value={phone} onChange={e=>setPhone(e.target.value)}/></label>{[['Username',profile!.username],['Email',profile!.email],['Employee ID / NPP',profile!.npp],['Role',profile!.role],['Unit',profile!.unit],['Region',profile!.region]].map(([label,value])=><label className="field" key={label}>{label}<span className="small">System-managed</span><input disabled value={value}/></label>)}</div><button className="btn primary" disabled={busy}>{busy?'Saving…':'Save Profile'}</button></form></Card></div></>;
}
