import { useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Download, X } from 'lucide-react';
import { useData } from '../hooks/useData';
import { emptyFilters, type CaseRecord } from '../lib/types';
import { exportCases, exportCSV, filterCases, groupCases, handlingHours, median, monthlyGroups, urgency } from '../lib/analytics';
import CaseFilters from '../components/CaseFilters';
import CaseTable from '../components/CaseTable';
import { Chart } from '../components/Charts';
import { Badge, Card, Empty, PageHead } from '../components/UI';
export default function Reports({signalsOnly=false}:{signalsOnly?:boolean}){
  const {cases,config}=useData();const navigate=useNavigate();
  const [filters,setFilters]=useState({...emptyFilters}),[detail,setDetail]=useState<{title:string;cases:CaseRecord[]}|null>(null);
  const [dimension,setDimension]=useState<'product'|'category'|'subcategory'|'region'>('product'),[exportType,setExportType]=useState('cases'),[faqAll,setFaqAll]=useState(false),[explore,setExplore]=useState('important');
  const filtered=useMemo(()=>filterCases(cases.filter(c=>!c.is_draft),filters,config),[cases,filters,config]);
  const regions=useMemo(()=>groupCases(filtered,'region'),[filtered]),products=useMemo(()=>groupCases(filtered,'product'),[filtered]),categories=useMemo(()=>groupCases(filtered,'category'),[filtered]),months=useMemo(()=>monthlyGroups(filtered),[filtered]);
  const hours=filtered.filter(c=>c.lifecycle==='Closed').map(c=>handlingHours(c,config));
  const top=groupCases(filtered,dimension).slice(0,8);
  const faq=useMemo(()=>{
    const map=new Map<string,CaseRecord[]>();for(const c of filtered){const k=c.category+' — '+c.subcategory;map.set(k,[...(map.get(k)||[]),c]);}return [...map.entries()].sort((a,b)=>b[1].length-a[1].length);
  },[filtered]);
  function drill(title:string,list:CaseRecord[]){setDetail({title,cases:list});requestAnimationFrame(()=>document.getElementById('managementDetail')?.scrollIntoView({behavior:'smooth',block:'start'}));}
  function exportReport(){if(exportType==='cases'){exportCases(filtered);return;}const groups=exportType==='regional'?regions:exportType==='product'?products:categories;exportCSV('tcams_'+exportType,['Dimension','Total','Open','Closed','Median TAT Hours'],groups.map(([key,list])=>[key,list.length,list.filter(c=>c.lifecycle!=='Closed').length,list.filter(c=>c.lifecycle==='Closed').length,median(list.filter(c=>c.actual_handling_hours!==null).map(c=>c.actual_handling_hours!)).toFixed(2)]));}
  const open=filtered.filter(c=>c.lifecycle!=='Closed'),waiting=filtered.filter(c=>c.lifecycle==='Waiting Support'),attention=filtered.filter(c=>urgency(c,config)==='Needs Attention');
  const signals=[{title:'Cases requiring attention',evidence:`${attention.length} of ${open.length} open cases have high priority, overdue follow-up, or elapsed TAT.`,interpretation:'Review the underlying cases and confirm the next action with the primary PIC.',list:attention}, {title:'Waiting for supporting units',evidence:`${waiting.length} cases are waiting for support.`,interpretation:'Check supporting-unit responses and follow-up dates.',list:waiting}, {title:'Regional concentration',evidence:regions[0]?`${regions[0][0]} accounts for ${regions[0][1].length} of ${filtered.length} filtered cases.`:'No regional data.',interpretation:'Review recurring topics in the busiest region before allocating resources.',list:regions[0]?.[1]||[]}];
  const exploreCases=explore==='all'?filtered:explore==='waiting'?waiting:explore==='attention'?attention:filtered.filter(c=>urgency(c,config)==='Needs Attention'||c.lifecycle==='Waiting Support'||c.priority==='High');
  return <><PageHead title={signalsOnly?'AI Insights':'Reports & Insights'} description="Explore trends, products, categories, regions, and the underlying cases."><select aria-label="Export report type" value={exportType} onChange={e=>setExportType(e.target.value)}><option value="cases">Current Filtered Cases</option><option value="regional">Regional Summary</option><option value="product">Product Summary</option><option value="category">Category Summary</option></select><button className="btn secondary" onClick={exportReport}><Download size={16}/>Export Current Report</button></PageHead>
  <CaseFilters report value={filters} onChange={f=>{setFilters(f);setDetail(null);}}/>
  <div className="executive-grid">{[{label:'Total Cases',value:filtered.length,list:filtered},{label:'Active Regions',value:regions.length,list:filtered},{label:'Open Cases',value:open.length,list:open},{label:'Waiting Support',value:waiting.length,list:waiting},{label:'Median TAT',value:hours.length?median(hours).toFixed(1)+' h':'—',list:filtered.filter(c=>c.lifecycle==='Closed')},{label:'Top Product',value:products[0]?.[0]||'—',list:products[0]?.[1]||[]}].map(item=><button key={item.label} className="executive-card dh-clickable" onClick={()=>drill(item.label,item.list)}><span>{item.label}</span><strong>{item.value}</strong><small>Explore supporting cases</small></button>)}</div>
  {detail?<Card title={detail.title} subtitle={`${detail.cases.length} cases under the current report filters`} className="management-detail" actions={<button className="btn secondary" onClick={()=>setDetail(null)} aria-label="Close drilldown"><X size={16}/></button>}><div id="managementDetail"><CaseTable cases={detail.cases} onOpen={c=>navigate('/cases/'+c.id)}/></div></Card>:null}
  {!filtered.length?<Card><Empty text="No case data is available for the selected report filters."/></Card>:null}
  {!signalsOnly && filtered.length?<>
  <div className="grid2"><Card title="Regional Activity" subtitle="Volume, top product, and operational status"><div className="region-list">{regions.map(([region,list])=><button className="region-rank-row dh-clickable" key={region} onClick={()=>drill('Regional Activity — '+region,list)}><strong>{region}</strong><span className="region-progress"><i style={{width:Math.max(3,list.length/filtered.length*100)+'%'}}/></span><span>{list.length.toLocaleString()} cases</span><small>{groupCases(list,'product')[0]?.[0]}</small></button>)}</div></Card><Card title="Monthly Case Volume" subtitle="Click a month to inspect its cases"><Chart labels={months.map(([m])=>m)} values={months.map(([,list])=>list.length)} onSelect={i=>drill('Monthly Case Volume — '+months[i][0],months[i][1])}/></Card></div>
  <div className="grid2"><Card title="Case Trend by Region"><Chart kind="line" labels={months.map(([m])=>m)} values={[]} series={regions.slice(0,5).map(([region])=>({label:region,values:months.map(([,list])=>list.filter(c=>c.region===region).length)}))} onSelect={i=>drill('Regional Trends — '+months[i][0],months[i][1])}/></Card><Card title="Regional Contribution to Total Cases"><Chart kind="doughnut" labels={regions.map(([r])=>r)} values={regions.map(([,list])=>list.length)} onSelect={i=>drill('Regional Contribution — '+regions[i][0],regions[i][1])}/></Card></div>
  <Card title="What Are Regions Asking About?" className="spaced" actions={<select aria-label="Analysis dimension" value={dimension} onChange={e=>setDimension(e.target.value as typeof dimension)}>{['product','category','subcategory','region'].map(x=><option key={x} value={x}>{x.charAt(0).toUpperCase()+x.slice(1)}</option>)}</select>}><Chart labels={top.map(([label])=>label)} values={top.map(([,list])=>list.length)} onSelect={i=>drill(top[i][0],top[i][1])}/></Card>
  <div className="grid2"><Card title="Regional × Category Analysis"><div className="table-wrap"><table className="heatmap"><thead><tr><th>Region</th>{categories.slice(0,6).map(([name])=><th key={name}>{name}</th>)}</tr></thead><tbody>{regions.slice(0,10).map(([region,list])=><tr key={region}><th>{region}</th>{categories.slice(0,6).map(([category])=>{const selected=list.filter(c=>c.category===category);return <td key={category}><button style={{background:`rgba(45,111,174,${.06+selected.length/(list.length||1)*.45})`}} onClick={()=>drill(region+' × '+category,selected)} aria-label={`${region}, ${category}: ${selected.length} cases`}>{selected.length}</button></td>;})}</tr>)}</tbody></table></div></Card><Card title="Typical Handling Time" subtitle="Closed cases only; operational reference"><div className="tat-reference"><strong>{hours.length?median(hours).toFixed(1):'—'}<span> hours median</span></strong><p className="small">Based on {hours.length.toLocaleString()} closed cases in the current filter context.</p></div><Chart labels={['< 1h','1–4h','4–8h','8–24h','≥ 24h']} values={[hours.filter(h=>h<1).length,hours.filter(h=>h>=1&&h<4).length,hours.filter(h=>h>=4&&h<8).length,hours.filter(h=>h>=8&&h<24).length,hours.filter(h=>h>=24).length]}/></Card></div>
  <Card title="Top 10 Frequently Asked Cases" className="analytics-accent spaced" actions={<button className="link" onClick={()=>setFaqAll(!faqAll)}>{faqAll?'Show Top 10':'View All'}</button>}><div className="table-wrap"><table><thead><tr><th>Topic</th><th>Cases</th><th>Top Product</th><th>Top Region</th></tr></thead><tbody>{(faqAll?faq:faq.slice(0,10)).map(([name,list])=><tr key={name}><td><button className="link" onClick={()=>drill(name,list)}>{name}</button></td><td>{list.length}</td><td>{groupCases(list,'product')[0]?.[0]}</td><td>{groupCases(list,'region')[0]?.[0]}</td></tr>)}</tbody></table></div></Card>
  </>:null}
  <Card title={signalsOnly?'Investigation Signals':'Emerging Signals'} className="spaced" subtitle="Evidence-based observations from your current case data"><div className="signal-grid">{signals.map(signal=><div className="signal-card" key={signal.title}><h4>{signal.title}</h4><p><b>Evidence:</b> {signal.evidence}</p><p><b>Suggested investigation:</b> {signal.interpretation}</p><button className="link" onClick={()=>drill(signal.title,signal.list)}>View Supporting Cases</button></div>)}</div>{signalsOnly?<p className="small spaced-text">These insights are derived from case data and rules. External AI generation is not configured.</p>:null}</Card>
  <Card title="Key Takeaways" className="spaced"><div className="takeaway-list"><p><strong>Inquiry concentration.</strong> {regions[0]?`${regions[0][0]} contributes ${Math.round(regions[0][1].length/(filtered.length||1)*100)}% of filtered inquiries.`:'No regional data.'}</p><p><strong>Product demand.</strong> {products[0]?`${products[0][0]} is the leading product with ${products[0][1].length} cases.`:'No product data.'}</p><p><strong>Recurring topic.</strong> {faq[0]?.[0]||'No topic data.'}</p></div></Card>
  <Card title="Explore Cases" actions={<select aria-label="Explore case mode" value={explore} onChange={e=>setExplore(e.target.value)}><option value="important">Important Cases</option><option value="attention">Needs Attention</option><option value="waiting">Waiting Support</option><option value="all">All Filtered Cases</option></select>}><div className="attention-list">{exploreCases.length?exploreCases.slice(0,12).map(c=><button className="attention-item" key={c.id} onClick={()=>navigate('/cases/'+c.id)}><div><strong>{c.ticket}</strong><p>{c.subject}</p><span className="small">{c.region} • {c.product} • {c.primary_pic_name}</span></div><Badge text={urgency(c,config)}/></button>):<Empty text="No cases in this view."/>}</div>{exploreCases.length>12?<button className="link" onClick={()=>drill('Explore Cases',exploreCases)}>View all {exploreCases.length} cases</button>:null}</Card>
  </>;
}
