import { useNavigate } from 'react-router-dom';
import { useData } from '../hooks/useData';
import { groupCases, handlingHours } from '../lib/analytics';
import { Card, PageHead } from '../components/UI';
import { Chart } from '../components/Charts';
export default function Workload(){
  const {cases,config}=useData();const navigate=useNavigate();
  const people=[...new Set(cases.flatMap(c=>[c.primary_pic_name,...c.collaborator_names]))].filter(p=>p && !['Unassigned','Not Available','Other'].includes(p));
  const rows=people.map(name=>{const all=cases.filter(c=>c.primary_pic_name===name||c.collaborator_names.includes(name));const open=all.filter(c=>c.lifecycle!=='Closed');return {name,all,open,closed:all.filter(c=>c.lifecycle==='Closed'),waiting:all.filter(c=>c.lifecycle==='Waiting Support')};});
  const products=groupCases(cases,'product').map(([name])=>name),categories=groupCases(cases,'category').map(([name])=>name);
  function matrix(title:string,dimensions:string[],key:'product'|'category'){return <Card title={title}><div className="table-wrap"><table className="heatmap"><thead><tr><th>PIC</th>{dimensions.map(d=><th key={d}>{d}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.name}><th>{row.name}</th>{dimensions.map(d=>{const list=row.all.filter(c=>c[key]===d);return <td key={d}><button onClick={()=>navigate('/cases?search='+encodeURIComponent(row.name))} aria-label={`${row.name}, ${d}: ${list.length} cases`}>{list.length}</button></td>;})}</tr>)}</tbody></table></div></Card>;}
  return <><PageHead title="Team Workload & Activity" description="Workload visibility, expertise mapping, and resource allocation."/><div className="grid2"><Card title="Cases by PIC"><Chart labels={people} values={rows.map(r=>r.all.length)}/></Card><Card title="Open vs Closed by PIC"><Chart labels={people} values={[]} series={[{label:'Open',values:rows.map(r=>r.open.length)},{label:'Closed',values:rows.map(r=>r.closed.length)}]}/></Card></div><div className="grid2"><Card title="Product Coverage by PIC"><Chart labels={people} values={rows.map(r=>new Set(r.all.map(c=>c.product)).size)}/></Card><Card title="Waiting Support Distribution"><Chart kind="doughnut" labels={people} values={rows.map(r=>r.waiting.length)}/></Card></div><div className="grid2">{matrix('PIC × Product',products,'product')}{matrix('PIC × Category',categories,'category')}</div><Card title="Workload Summary"><div className="table-wrap"><table><thead><tr><th>PIC</th><th>Total</th><th>Closed</th><th>Open</th><th>Waiting</th><th>Average Open Aging</th><th>Products</th></tr></thead><tbody>{rows.map(r=><tr key={r.name}><td>{r.name}</td><td>{r.all.length}</td><td>{r.closed.length}</td><td>{r.open.length}</td><td>{r.waiting.length}</td><td>{r.open.length?(r.open.reduce((a,c)=>a+handlingHours(c,config),0)/r.open.length).toFixed(1)+' h':'—'}</td><td>{[...new Set(r.all.map(c=>c.product))].join(', ')}</td></tr>)}</tbody></table></div></Card></>;
}
